language: ruby
rvm:
  - 1.9.3
install:
  - sudo apt-get update -q
  #- sudo apt-get upgrade -y
  # workaround to get lxc installed, thanks https://github.com/dergachev/travis-test/blob/master/script.sh#L14-20
  - |
    cat <<EOF | sudo tee /usr/sbin/policy-rc.d
    #!/bin/sh
    exit 101
    EOF
  - sudo chmod 755 /usr/sbin/policy-rc.d
  - sudo apt-get install lxc
  - sudo apt-get install redir htop btrfs-tools vim apparmor-utils linux-image-generic linux-headers-generic
  - sudo aa-complain /usr/bin/lxc-start
  - sudo wget -nv http://files.vagrantup.com/packages/95d308caaecd139b8f62e41e7add0ec3f8ae3bd1/vagrant_1.2.3_x86_64.deb
  - sudo dpkg -i vagrant_1.2.3_x86_64.deb
  - sudo vagrant plugin install vagrant-lxc
env:
  global:
    - VAGRANT_DEFAULT_PROVIDER=lxc
    - USE_LXC_BRIDGE=false
script:
  - vagrant up
  - vagrant status
  - vagrant ssh -C 'ls -la'
after-script:
  - vagrant destroy